sudo: required

services:
  - docker

before_install:
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash

script: docker build -t nanobox/pod-sidecar-narc -f Dockerfile .

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/pod-sidecar-narc .
  - docker-squash -t ${NAMESPACE}/pod-sidecar-narc:squashed --tmp-dir /var/tmp/squasher ${NAMESPACE}/pod-sidecar-narc
  - docker tag ${NAMESPACE}/pod-sidecar-narc:squashed ${NAMESPACE}/pod-sidecar-narc:beta;
  - docker push ${REMOTE}${NAMESPACE}/pod-sidecar-narc:beta;
  - 'if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/pod-sidecar-narc:squashed ${NAMESPACE}/pod-sidecar-narc:latest;
    docker push ${REMOTE}${NAMESPACE}/pod-sidecar-narc:latest;
    else
    docker tag ${NAMESPACE}/pod-sidecar-narc:squashed ${NAMESPACE}/pod-sidecar-narc:${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/pod-sidecar-narc:${BRANCH//\//_};
    fi'
